export const NigerianState = {
  ABIA: "ABIA",
  ADAMAWA: "ADAMAWA",
  AKWA_IBOM: "AKWA_IBOM",
  ANAMBRA: "ANAMBRA",
  BAUCHI: "BAUCHI",
  BAYELSA: "BAYELSA",
  BENUE: "BENUE",
  BORNO: "BORNO",
  CROSS_RIVER: "CROSS_RIVER",
  DELTA: "DELTA",
  EBONYI: "EBONYI",
  EDO: "EDO",
  EKITI: "EKITI",
  ENUGU: "ENUGU",
  FCT: "FCT",
  GOMBE: "GOMBE",
  IMO: "IMO",
  JIGAWA: "JIGAWA",
  KADUNA: "KADUNA",
  KANO: "KANO",
  KATSINA: "KATSINA",
  KEBBI: "KEBBI",
  KOGI: "KOGI",
  KWARA: "KWARA",
  LAGOS: "LAGOS",
  NASARAWA: "NASARAWA",
  NIGER: "NIGER",
  OGUN: "OGUN",
  ONDO: "ONDO",
  OSUN: "OSUN",
  OYO: "OYO",
  PLATEAU: "PLATEAU",
  RIVERS: "RIVERS",
  SOKOTO: "SOKOTO",
  TARABA: "TARABA",
  YOBE: "YOBE",
  ZAMFARA: "ZAMFARA",
} as const;

export type NigerianState =
  (typeof NigerianState)[keyof typeof NigerianState];